/** Section and shared-item types inferred from the runtime schemas. */
export type {
  AnswerProps,
  AuthorityProps,
  ContactFormProps,
  ContactInfoProps,
  CTAProps,
  FAQItem,
  FAQProps,
  FormField,
  HeroProps,
  ProcessProps,
  ProofProps,
  ProofStat,
  Section,
  SectionPropsMap,
  SectionType,
  ServiceItem,
  ServicesProps,
  TestimonialItem,
  TestimonialsProps,
  TitledItem,
  WhyChooseUsProps,
} from "../lib/content-schema";
