-- Leads — identified, and only created on explicit request.
--
-- Depends on quiz_sessions (000002) and partners (000003).

create table if not exists leads (
  id                     uuid primary key default gen_random_uuid(),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  session_id             uuid references quiz_sessions (id) on delete set null,

  full_name              text not null check (length(full_name) between 1 and 200),
  email                  text not null check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  phone                  text check (phone is null or length(phone) <= 40),
  zip                    text not null check (zip ~ '^\d{5}(-\d{4})?$'),
  street_address         text,

  -- Two columns, deliberately. `notes` is the homeowner's own words;
  -- `recommendation_summary` is generated by the engine. Composed into one
  -- string they can never be separated again, and the homeowner's own account
  -- of their problem is the more valuable half.
  notes                  text check (length(notes) <= 5000),
  recommendation_summary text check (length(recommendation_summary) <= 5000),

  -- TCPA. Store the exact wording consented to and when, not just a boolean —
  -- a bare true is not defensible if consent is ever challenged.
  contact_consent        boolean not null default false,
  consent_text           text,
  consent_at             timestamptz,

  photo_urls             text[],

  assigned_partner       uuid references partners (id) on delete set null,
  assigned_at            timestamptz,
  status                 text not null default 'new'
                         check (status in ('new','assigned','contacted','quoted','won','lost','invalid')),

  -- Copied from the session at submission. Drives the SMS decision.
  urgent                 boolean not null default false,
  ip_hash                text
);

create index if not exists leads_created_idx on leads (created_at desc);
create index if not exists leads_status_idx on leads (status);

-- Supports the 10-minute duplicate check in /api/lead, which is what stops a
-- double-click producing two rows and Rev calling the same homeowner twice.
create index if not exists leads_dedupe_idx on leads (email, zip, created_at desc);
